"""Add conversation snapshot

Revision ID: a5a64517b4cf
Revises: eb94db64aeb4
Create Date: 2026-04-10 10:17:36.449801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a5a64517b4cf'
down_revision: Union[str, Sequence[str], None] = 'eb94db64aeb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_snapshots_contact_id'), 'conversation_snapshots', ['contact_id'], unique=False)
    op.create_index(op.f('ix_conversation_snapshots_id'), 'conversation_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_snapshots_user_id'), 'conversation_snapshots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_snapshots_user_id'), table_name='conversation_snapshots')
    op.drop_index(op.f('ix_conversation_snapshots_id'), table_name='conversation_snapshots')
    op.drop_index(op.f('ix_conversation_snapshots_contact_id'), table_name='conversation_snapshots')
    op.drop_table('conversation_snapshots')
    # ### end Alembic commands ###
