"""add calendar connections table

Revision ID: eb94db64aeb4
Revises: 1e797201aab8
Create Date: 2026-04-08 09:59:01.036882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb94db64aeb4'
down_revision: Union[str, Sequence[str], None] = '1e797201aab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_connections_id'), 'calendar_connections', ['id'], unique=False)
    op.create_index(op.f('ix_calendar_connections_user_id'), 'calendar_connections', ['user_id'], unique=True)
    op.add_column('activities', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(None, 'deals', 'deal_stages', ['stage_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_column('activities', 'data')
    op.drop_index(op.f('ix_calendar_connections_user_id'), table_name='calendar_connections')
    op.drop_index(op.f('ix_calendar_connections_id'), table_name='calendar_connections')
    op.drop_table('calendar_connections')
    # ### end Alembic commands ###
